//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControllerActionForRole
    {
        public PhotoLibraryHelper.Actions ControllerId { get; set; }
        public PhotoLibraryHelper.Actions ActionId { get; set; }
        public PhotoLibraryHelper.UserRoles RoleId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastChanged { get; set; }
    
        public virtual ControllerAction ControllerAction { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
