//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControllerAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControllerAction()
        {
            this.ControllerActionForRoles = new HashSet<ControllerActionForRole>();
        }
    
        public PhotoLibraryHelper.Controllers ControllerId { get; set; }
        public PhotoLibraryHelper.Actions ActionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastChanged { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Controller Controller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControllerActionForRole> ControllerActionForRoles { get; set; }
    }
}
