//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoTheme
    {
        public int PhotoId { get; set; }
        public int ThemeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastChanged { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
