//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotoLibraryEntities : DbContext
    {
        public PhotoLibraryEntities()
            : base("name=PhotoLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Community> Communities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<PersonalPhoto> PersonalPhotoes { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<PhotoTheme> PhotoThemes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<ThemeImage> ThemeImages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCommunity> UserCommunities { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Controller> Controllers { get; set; }
        public virtual DbSet<ControllerAction> ControllerActions { get; set; }
        public virtual DbSet<ControllerActionForRole> ControllerActionForRoles { get; set; }
    }
}
