//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibraryHelper
{
    using System;
    
    public enum UserRoles : int
    {
        AdminRole = 1,
        PhotographerRole = 2,
        GuestRole = 3
    }
}
